version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout
      - run:
          name: Run tests
          command: make
      - run:
          name: Upload Codecov report
          command: make codecov

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
